AWS_ACCESS_KEY: "AKIAJOCV4NMLTR6OPSUQ"
AWS_SECRET_KEY: "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"
AWS_BUCKET:     "creeland-flixter-firehose"
AWS_REGION:     "us-east-1"

SECRET_KEY: "sk_test_2zbDASydKtJOb3hRFpAWCwWG"
PUBLISHABLE_KEY: "pk_test_s3zDrNbLVTXMAj6ODfrRpSoN"